import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ButtonProvider } from '@/context/ButtonContext'
import Provider from '@/context/provider'
import { ThemeProvider } from '@material-tailwind/react'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Provider>
    <ButtonProvider>
      <body className={inter.className}>{children}</body>
      </ButtonProvider>
      </Provider>

    </html>
  )
}
